version: "3"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=USER1
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=DB1
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge